import argparse, json, os
ap=argparse.ArgumentParser(description='Render profile.json -> profile.md')
ap.add_argument('--output-dir',default='reports/data_quality',help='directory holding profile.json; profile.md is written there (default: %(default)s)')
A=ap.parse_args()
P=os.path.abspath(A.output_dir)
R=json.load(open(os.path.join(P,'profile.json'),encoding='utf-8'));F=R['files'];G=R['ground_truth'];PR=R['params']
SRC=[t for t in F if t!='gt']
L=["# AMLC 2026 Business Entity Resolution: data profile","",
f"Generated by profile.py (duckdb {R['duckdb_version']}, memory_limit {PR['memory_limit']}, {PR['threads']} threads). Runtime {R['runtime_s']} s. All numbers are measured.","",
"## 1. Rows, duplicate IDs, ID overlap","","| file | rows (excl. header) | wc -l | distinct ids | dup id values | exact dup rows | bad prefix |","|---|---|---|---|---|---|---|"]
for t,i in F.items():
    L.append(f"| {t} | {i['rows']:,} | {R['wc_l_lines_incl_header'][t]:,} | {i['distinct_ids']:,} | {i['duplicate_id_values']} | {i.get('exact_duplicate_rows','-')} | {i.get('ids_bad_prefix','-')} |")
ov=R['train_test_id_overlap']
L+=["",f"Train/test ID overlap ({len([k for k in ov if k!='within_train_cross_source'])} combinations): "+", ".join(f"{k}={v}" for k,v in ov.items() if k!='within_train_cross_source'),
"Within-train cross-source overlap: "+", ".join(f"{k}={v}" for k,v in ov['within_train_cross_source'].items()),"",
"## 2. Null or empty rate, countries, non-Latin names","","| file | name null/blank | address null/blank | country null/blank | countries (top 15) | non-Latin names | Devanagari names |","|---|---|---|---|---|---|---|"]
for t in SRC:
    i=F[t];ne=i['null_empty']
    L.append(f"| {t} | {ne['business_name']['null_or_blank_rate']:.4%} | {ne['business_address']['null_or_blank_rate']:.4%} ({ne['business_address']['null']+ne['business_address']['blank_whitespace_only']:,}) | {ne['country']['null_or_blank_rate']:.4%} | "+", ".join(f"{k} {v:,}" for k,v in i['country_top15'])+f" | {i['names_nonlatin_letter']['rate_of_nonnull_names']:.2%} ({i['names_nonlatin_letter']['count']:,}) | {i['names_devanagari']['rate_of_nonnull_names']:.2%} ({i['names_devanagari']['count']:,}) |")
L+=["","Null entity_id counts: "+", ".join(f"{t}={F[t]['null_id']}" for t in F)+". Non-Latin = name contains at least one letter outside Latin script (regex `[^\\p{Latin}\\P{L}]`).","",
"### Primary script of non-Latin names",""]
for t in SRC:
    ps=F[t]['name_script_primary_counts']
    if ps['nonlatin_total']==0: L.append(f"- {t}: no non-Latin names"); continue
    L.append(f"- {t}: "+", ".join(f"{k} {v:,}" for k,v in ps['counts'].items())+f" | sum {ps['sum']:,} vs non-Latin total {ps['nonlatin_total']:,} (equal: {ps['sum_equals_nonlatin_total']})")
L+=["",f"Rule: {F[SRC[0]]['name_script_primary_counts']['note']}. Scripts measured: {', '.join(F[SRC[0]]['name_script_primary_counts']['scripts_measured'])}.","","### Names containing each script (overlapping)",""]
for t in SRC:
    cc=F[t]['name_script_contains_counts']
    L.append(f"- {t}: "+", ".join(f"{k} {v:,}" for k,v in cc['counts'].items()))
L+=["",f"Rule: {F[SRC[0]]['name_script_contains_counts']['note']}.","","### Non-Latin rate by country",""]
for t,d in R['nonlatin_by_country'].items(): L.append(f"- {t}: "+", ".join(f"{k} {v['nonlatin_rate']:.2%} ({v['nonlatin']:,}/{v['rows']:,}; other script {v['nonlatin_other_script']:,})" for k,v in d.items()))
L+=["","## 3. Length (Unicode chars, non-null values)","","| file | name median | name p95 | name max | addr median | addr p95 | addr max |","|---|---|---|---|---|---|---|"]
for t in SRC:
    n,a=F[t]['length_stats']['business_name'],F[t]['length_stats']['business_address']
    L.append(f"| {t} | {n['median_chars']} | {n['p95_chars']} | {n['max_chars']} | {a['median_chars']} | {a['p95_chars']} | {a['max_chars']} |")
d=G['matches_per_s1_distribution_[count,frac]'];ns=G['nonsingleton_s1_with']
L+=["","## 4. Ground truth","",f"- GT rows {G['gt_rows']:,}; singletons {G['singletons']:,} = {G['singleton_rate']:.4%}",
"- Matches per S1: "+", ".join(f"{k}: {v[0]:,} ({v[1]:.2%})" for k,v in d.items()),
f"- Mean {G['mean_matches_all_s1']} (all S1), {G['mean_matches_nonsingleton']} (non-singleton); median (non-singleton) {G['median_matches_nonsingleton']}; max {G['max_matches']}",
f"- Pairs {G['total_pairs']:,}: S2 {G['pairs_S2']:,} ({G['frac_S2']:.2%}), S3 {G['pairs_S3']:,} ({G['pairs_S3']/G['total_pairs']:.2%})",
"- Non-singleton S1: "+", ".join(f"{k} {v:,}" for k,v in ns.items()),
f"- Hygiene: empty tokens {G['empty_token_in_lists']}, whitespace in tokens {G['token_with_whitespace']}, duplicate IDs within a list {G['intra_list_duplicate_ids']}, bad prefix {G['bad_prefix_tokens']}"]
ca=G['check_a_multi_parent']
L+=["","## 5. Check (a): one S2/S3 ID under several S1 IDs","",f"- {ca['ids_under_more_than_one_s1']:,} of {ca['distinct_matched_ids']:,} matched IDs (S2 {ca['S2']:,}, S3 {ca['S3']:,}); max multiplicity {ca['max_multiplicity']}",
"- Multiplicity distribution: "+", ".join(f"{k}: {v:,}" for k,v in ca['multiplicity_distribution']),"",
"## 6. Check (b): train S2/S3 records never in the GT, and orphan IDs",""]
for s,v in G['check_b_unreferenced_and_orphans'].items(): L.append(f"- {s}: {v['never_in_gt']:,} of {v['train_distinct_ids']:,} never in the GT ({v['never_in_gt_pct']:.2f}%); GT IDs missing from train_source: {v['gt_ids_missing_from_train_source']} (of those found in test: {v['of_those_found_in_test_source']})")
s=G['s1_set'];c=G['country_agreement_sample']
L+=["","## 7. GT S1 set compared with train_source1","",f"- GT IDs not in train_s1: {s['gt_s1_not_in_train_s1']}; train_s1 IDs not in GT: {s['train_s1_not_in_gt']}; identical = {s['identical']}","",
"## 8. Country agreement","",f"- Sample: {c['method']}",
f"- {c['sampled_pairs']:,} pairs sampled, {c['pairs_with_both_records_found']:,} with both records found: exact country match {c['exact_equal']:,} ({c['exact_rate_of_both_nonnull']:.2%}); S2 {c['S2_rate']:.2%}, S3 {c['S3_rate']:.2%}",
"- Top disagreeing pairs: "+(", ".join(f"{a}->{b} {n:,}" for a,b,n in c['top_disagreeing_country_pairs']) or "none"),""]
vs=R['scoring_script']
L+=["## Scoring script","",f"- Path: {vs['path']} (exists: {vs['exists']})"]
if vs['exists']:
    L+=[f"- Computes a score: {vs['computes_score']}; reads a ground_truth.tsv: {vs['reads_ground_truth_file']}",
        "- Keyword mentions: "+", ".join(f"{k}={v}" for k,v in vs['mentions'].items()),
        f"- MATCHING_HEADER = {vs['MATCHING_HEADER']}; CANDIDATE_HEADER = {vs['CANDIDATE_HEADER']}; DELIM = {vs['DELIM']}"]+[f"- {r}" for r in vs['rules']]
L+=["",f"Timing (s): "+", ".join(f"{k}={v}" for k,v in R['timing_s'].items()),""]
open(os.path.join(P,'profile.md'),'w',encoding='utf-8').write("\n".join(L))
print('wrote',os.path.join(P,'profile.md'))
