import json
R=json.load(open('profile.json'));F=R['files'];G=R['ground_truth']
L=["# AMLC 2026 Business Entity Resolution: data profile","",f"Generated by profile.py (duckdb {R['duckdb_version']}, memory_limit 3GB, 4 threads). Main runtime {R['runtime_s']} s. All numbers are measured.","",
"## 1. Rows, duplicate IDs, ID overlap","","| file | rows (excl. header) | wc -l | distinct ids | dup id values | exact dup rows | bad prefix |","|---|---|---|---|---|---|---|"]
for t,i in F.items():
    L.append(f"| {t} | {i['rows']:,} | {R['wc_l_lines_incl_header'][t]:,} | {i['distinct_ids']:,} | {i['duplicate_id_values']} | {i.get('exact_duplicate_rows','-')} | {i.get('ids_bad_prefix','-')} |")
L+=["","Train/test ID overlap (all 9 combinations): "+", ".join(f"{k}={v}" for k,v in R['train_test_id_overlap'].items() if k!='within_train_cross_source'),"",
"## 2. Null or empty rate, countries, non-Latin names","","| file | name null/blank | address null/blank | country null/blank | countries (top 15) | non-Latin names | Devanagari names |","|---|---|---|---|---|---|---|"]
for t,i in F.items():
    if t=='gt': continue
    ne=i['null_empty']
    L.append(f"| {t} | {ne['business_name']['null_or_blank_rate']:.4%} | {ne['business_address']['null_or_blank_rate']:.4%} ({ne['business_address']['null']+ne['business_address']['blank_whitespace_only']:,}) | {ne['country']['null_or_blank_rate']:.4%} | "+", ".join(f"{k} {v:,}" for k,v in i['country_top15'])+f" | {i['names_nonlatin_letter']['rate_of_nonnull_names']:.2%} ({i['names_nonlatin_letter']['count']:,}) | {i['names_devanagari']['rate_of_nonnull_names']:.2%} ({i['names_devanagari']['count']:,}) |")
L+=["","entity_id is never null in any file. 'Non-Latin' means the name contains at least one letter outside Latin script (regex `[^\\p{Latin}\\P{L}]`).","","Script counts in names (a name can contain more than one script):"]
for t,i in F.items():
    if t!='gt' and i['name_nonlatin_top_scripts']: L.append(f"- {t}: "+", ".join(f"{k} {v:,}" for k,v in i['name_nonlatin_top_scripts'].items())+" (the rest is Oriya)")
L+=["","Non-Latin rate by country:"]
for t,d in R['nonlatin_by_country'].items(): L.append(f"- {t}: "+", ".join(f"{k} {v['nonlatin_rate']:.2%}" for k,v in d.items()))
L+=["","## 3. Length (Unicode chars, non-null values)","","| file | name median | name p95 | name max | addr median | addr p95 | addr max |","|---|---|---|---|---|---|---|"]
for t,i in F.items():
    if t=='gt': continue
    n,a=i['length_stats']['business_name'],i['length_stats']['business_address']
    L.append(f"| {t} | {n['median_chars']} | {n['p95_chars']} | {n['max_chars']} | {a['median_chars']} | {a['p95_chars']} | {a['max_chars']} |")
d=G['matches_per_s1_distribution_[count,frac]']
L+=["","## 4. Ground truth","",f"- GT rows {G['gt_rows']:,}; singletons {G['singletons']:,} = {G['singleton_rate']:.4%}",
"- Matches per S1: "+", ".join(f"{k}: {v[0]:,} ({v[1]:.2%})" for k,v in d.items()),
f"- Mean {G['mean_matches_all_s1']} (all S1), {G['mean_matches_nonsingleton']} (non-singleton); median (non-singleton) {G['median_matches_nonsingleton']}; max {G['max_matches']}",
f"- Pairs {G['total_pairs']:,}: S2 {G['pairs_S2']:,} ({G['frac_S2']:.2%}), S3 {G['pairs_S3']:,} ({1-G['frac_S2']:.2%})",
f"- Non-singleton S1: S2 only {G['nonsingleton_s1_with']['S2_only']:,}, S3 only {G['nonsingleton_s1_with']['S3_only']:,}, both {G['nonsingleton_s1_with']['both']:,}",
f"- Hygiene: empty tokens {G['empty_token_in_lists']}, whitespace in tokens {G['token_with_whitespace']}, duplicate IDs within a list {G['intra_list_duplicate_ids']}, bad prefix {G['bad_prefix_tokens']}","",
"## 5. Check (a): one S2/S3 ID under several S1 IDs","",f"- {G['check_a_multi_parent']['ids_under_more_than_one_s1']} of {G['check_a_multi_parent']['distinct_matched_ids']:,} matched IDs; max multiplicity {G['check_a_multi_parent']['max_multiplicity']}. The GT is a strict partition.","",
"## 6. Check (b): train S2/S3 records never in the GT, and orphan IDs",""]
for s,v in G['check_b_unreferenced_and_orphans'].items(): L.append(f"- {s}: {v['never_in_gt']:,} of {v['train_distinct_ids']:,} never in the GT ({v['never_in_gt_pct']:.2f}%); GT IDs missing from train_source: {v['gt_ids_missing_from_train_source']}")
s=G['s1_set'];c=G['country_agreement_sample']
L+=["","## 7. GT S1 set compared with train_source1","",f"- GT IDs not in train_s1: {s['gt_s1_not_in_train_s1']}; train_s1 IDs not in GT: {s['train_s1_not_in_gt']}; identical = {s['identical']}","",
"## 8. Country agreement (reservoir sample, seed 42)","",f"- {c['sampled_pairs']:,} pairs sampled: exact country match {c['exact_equal']:,} ({c['exact_rate_of_both_nonnull']:.2%}); S2 {c['S2_rate']:.2%}, S3 {c['S3_rate']:.2%}","",
"## Scoring script (validate_submission.py)","",
"- It is a format validator only. It never reads the ground truth and does not compute F0.5 or any other score. The word F0.5 does not appear in it, and it has no singleton scoring logic.",
"- Rules it enforces: TAB-separated, header exactly `source1_entity_id\tmatched_entity_ids`, one row per test_source1 S1 ID (none missing, none extra, no duplicate rows), an empty list means no match (singleton), IDs comma-separated with S2-/S3- prefix only, no S1 self-matches, no duplicates within a list, UTF-8.",
"- Optional `--check-ids` flags IDs that do not exist in test S2/S3. Per its docstring, a nonexistent ID only lowers the score and does not cause rejection.",
"- Optional candidate_pairs.tsv (header `source1_entity_id\tcandidate_entity_ids`) gets the same checks, plus a warning (never a failure) when final matches are not a subset of the candidates. The docstring says it is expected in the final zip.",""]
open('profile.md','w').write("\n".join(L))
